### ISSUE TITLE
Funnel graph does not fit all the time when you resize report on dashboard page

### ISSUE THREAD

**Issue by Himmetk** [rakam-io/rakam-ui#84] opened 2017-06-19 10:40 UTC

**Comment by Himmetk** [comment] 2017-06-20 08:34
@buremba  also cash issue

**Comment by buremba** [comment] 2017-07-06 00:02
@Himmetk what was the cash issue?

**Comment by buremba** [comment] 2017-07-06 01:21
Could you please share the dashboard url with me? I couldn't reproduce the issue.

**Comment by buremba** [comment] 2017-08-08 01:59
Still waiting for the dashboard url.

**Comment by buremba** [comment] 2017-09-12 23:36
@Himmetk Still waiting for the dashboard url. :)

**Comment by Himmetk** [comment] 2017-09-13 09:37
sorry, I forgot this I cannot reproduce the issue cause I removed the dashboard.

**Comment by buremba** [comment] 2017-09-13 09:51
OK then, I'm closing the issue. Feel free to create or reopen if you see the bug again.

**Closed as completed by buremba** 2017-09-13 09:51 UTC
