### ISSUE TITLE
need provision to create funnels to be split by month, day, hour of _time column

### ISSUE THREAD

**Issue by RameshByndoor** [rakam-io/rakam-ui#105] opened 2017-08-01 11:51 UTC
As of now funnels can be grouped by only commons columns available in table,It's very good and important to have group by month, day, hour for _time column. It's not possible as of now.

**Comment by buremba** [comment] 2017-08-07 20:22
Duplicate of https://github.com/rakam-io/rakam/issues/71

**Closed as completed by buremba** 2017-08-07 20:22 UTC
